// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMYjMbu3gpS2xVAisl0oaH3dv1pUgT0ns',
    appId: '1:1031670738306:web:e2e47cd44814bc22f9f39b',
    messagingSenderId: '1031670738306',
    projectId: 'agroly-9eb28',
    authDomain: 'agroly-9eb28.firebaseapp.com',
    storageBucket: 'agroly-9eb28.firebasestorage.app',
    measurementId: 'G-DJTG1L6VKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu_0Gb85zcHG_TWt6dIbXXKmeguoEJ5ic',
    appId: '1:1031670738306:android:3b10226ae28c407af9f39b',
    messagingSenderId: '1031670738306',
    projectId: 'agroly-9eb28',
    storageBucket: 'agroly-9eb28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyCY_KVs7HeAYcHVUxiaTPiY1R27GT_gU',
    appId: '1:1031670738306:ios:f2da1d7002e3d000f9f39b',
    messagingSenderId: '1031670738306',
    projectId: 'agroly-9eb28',
    storageBucket: 'agroly-9eb28.firebasestorage.app',
    iosBundleId: 'com.example.agroly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyCY_KVs7HeAYcHVUxiaTPiY1R27GT_gU',
    appId: '1:1031670738306:ios:f2da1d7002e3d000f9f39b',
    messagingSenderId: '1031670738306',
    projectId: 'agroly-9eb28',
    storageBucket: 'agroly-9eb28.firebasestorage.app',
    iosBundleId: 'com.example.agroly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMYjMbu3gpS2xVAisl0oaH3dv1pUgT0ns',
    appId: '1:1031670738306:web:554585222018cc61f9f39b',
    messagingSenderId: '1031670738306',
    projectId: 'agroly-9eb28',
    authDomain: 'agroly-9eb28.firebaseapp.com',
    storageBucket: 'agroly-9eb28.firebasestorage.app',
    measurementId: 'G-36S5Z6JNC4',
  );
}
